SmartHApp/SmartHApp/SmartHApp/Controllers/MeteoStationController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using DataBaseInto.BaseWork;

using SmartHApp.Models;

namespace SmartHApp.Controllers
{
    public class MeteoStationController : BaseController
    {
        // GET: MeteoStation
        public ActionResult OpenMain()
        {
            var allmodel = new AllMeteoViewMpdels();
            allmodel.Sensors = new List<MeteoViewModel>();
            var getsensors = Service.GetAllMeteo();
            if (getsensors.Count != 0)
            {
                foreach (var sensor in getsensors)
                {
                    var sensormodel = new MeteoViewModel();
                    sensormodel.Id = sensor.Id;
                    sensormodel.Name = sensor.Name;
                    sensormodel.Type = sensor.TypeDevice;
                    if (sensor.DispaysDevice != null)
                    {
                        sensormodel.Displayes = sensor.DispaysDevice.Value;
                    }
                    allmodel.Sensors.Add(sensormodel);
                }
                var sumtemp = allmodel.Sensors.Where(x => x.Type == false).Sum(x => x.Displayes);
                allmodel.AverageTemp = (sumtemp / allmodel.Sensors.Count(x => x.Type == false)).ToString(CultureInfo.InvariantCulture);
                var sumpress = allmodel.Sensors.Where(x => x.Type == true).Sum(x => x.Displayes);
                allmodel.AveragePress = (sumpress / allmodel.Sensors.Count(x => x.Type == true)).ToString(CultureInfo.InvariantCulture);
            }
            return View(allmodel);
        }

        public JsonResult SetMainTemp(string temper)
        {
            double temp;
            double.TryParse(temper, out temp);
            Service.ChangeMaintemp(temp);
            Service.LogAction(DateTime.Now, string.Format("Середню температуру змінено на {0}",temper), "Змінено" );
            return Json("success");
        }

        public JsonResult SetMainPress(string temper)
        {
            double temp;
            double.TryParse(temper, out temp);
            Service.ChangeMainpress(temp);
            Service.LogAction(DateTime.Now, string.Format("Cередній тиск змінено на {0}", temper), "Змінено");
            return Json("success");
        }
        public JsonResult SetSensorTemp(string temper,string id)
        {
            double temp;
            int idn;
            double.TryParse(temper, out temp);
            int.TryParse(id, out idn);
            string name = Service.ChangeSensortemp(temp, idn);
            Service.LogAction(DateTime.Now, string.Format("Cередній температуру на \"{0}\" змінено на {1}", name, temper), "Змінено");
            return Json("success");
        }

        public JsonResult SetSensorPress(string temper, string id)
        {
            double temp;
            int idn;
            double.TryParse(temper, out temp);
            int.TryParse(id, out idn);
            string name = Service.ChangeSensorpress(temp,idn);
            Service.LogAction(DateTime.Now, string.Format("Cередній тиск на \"{0}\" змінено на {1}",name, temper), "Змінено");
            return Json("success");
        }

    }
}

SmartHApp/SmartHApp/SmartHApp/Views/MeteoStation/OpenMain.cshtml
@model SmartHApp.Models.AllMeteoViewMpdels

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Scripts.Render("~/bundles/meteo")
<div class="row">
    <div class="col-md-6">
        <div class="btn-group-vertical padding10emtop">
            <button type="button" onclick="showtemp()" class="btn btn-primary width250 ">Температура</button>
            <button type="button" onclick="showpress()" class="btn btn-primary width250 ">Тиск</button>
        </div>
    </div>
    <div class="col-md-6">
        <div id="temperature" class="temperature hidden padding4emtop">
            <div>
                <div class="row text-center">
                    <div class="row">
                        <img style="height: 120px" src="../../Images/c-temperature-folded-icon.png" />
                    </div>
                    <div id="temperaturestate" class="row padding1emonlytop">
                        <div style="transform: translateY(50%); font-size: 50px" class="col-xs-6 normalcolor">@Model.AverageTemp &deg;С</div>
                        <div class="col-xs-6"><input type="button" onclick="editMaintemp()" class="buttonBlue" value="Змінити" /></div>
                    </div>
                    <div id="temperatureedit" class="row hidden padding1emonlytop">
                        <div style="font-size: 30px" class="col-xs-6"><input style="width: 70%; " id="numberedittemp" type="number" placeholder="@Model.AverageTemp" />&deg;С</div>
                        <div class="col-xs-6"><input style="" type="button" onclick="saveMaintemp()" class="buttonBlue" value="Зберегти" /></div>
                    </div>
                </div>
                <div class="row padding2emtop">
                    @foreach (var sensor in Model.Sensors.Where(x => x.Type == false))
                    {
                    <div style="transform: translateY(50%)" class="row backgrondlist">
                        <div class="col-xs-4">
                            <img style="height: 40px;" src="../../Images/term.png" />
                        </div>
                        <div class="col-xs-4 text-center">@sensor.Name</div>
                        <div class="col-xs-4 text-center">
                            <div id=@string.Format("statesensortemp{0}",@sensor.Id)>
                                <div>@sensor.Displayes &deg;С</div>
                                <div><input type="button" onclick="editsensortemp(@sensor.Id)" class="buttonBlue" value="Змінити" /></div>
                            </div>
                            <div id="@string.Format("editsensortemp{0}",@sensor.Id)" class="hidden">
                                <div><input style="width: 70%; " id="@string.Format("numbersensortemp{0}",@sensor.Id)" type="number" placeholder="@sensor.Displayes" /></div>
                                <div><input type="button" onclick="savesensortemp(@sensor.Id)" style="max-height: 60%" class="buttonBlue" value="Зберегти" /></div>
                            </div>
                        </div>
                    </div>
                    }
                </div>
            </div>

        </div>
        <div id="press" class="press hidden padding4emtop">
            <div class="row text-center">
                <div class="row">
                    <img style="height: 120px" src="../../Images/Sensor-music-player-Icon.png" />
                </div>
                <div id="pressstate" class="row padding1emonlytop">
                    <div style="transform: translateY(50%); font-size: 30px" class="col-xs-6 normalcolor">@Model.AveragePress мм рт. ст. </div>
                    <div class="col-xs-6"><input type="button" onclick="editMainpress()" class="buttonBlue" value="Змінити" /></div>
                </div>
                <div id="pressedit" class="row hidden padding1emonlytop">
                    <div style="font-size: 30px" class="col-xs-6"><input style="width: 70%; " id="numbereditpress" type="number" placeholder="@Model.AveragePress" /></div>
                    <div class="col-xs-6"><input style="" type="button" onclick="saveMainpress()" class="buttonBlue" value="Зберегти" /></div>
                </div>
            </div>
            <div class="row padding2emtop">
                @foreach (var sensor in Model.Sensors.Where(x => x.Type == true))
                {
                <div style="transform: translateY(50%)" class="row backgrondlist">
                    <div class="col-xs-4">
                        <img style="height: 40px;" src="../../Images/54-512.png" />
                    </div>
                    <div class="col-xs-4 text-center">@sensor.Name</div>
                    <div class="col-xs-4 text-center">
                        <div id=@string.Format("statesensorpress{0}",@sensor.Id)>
                            <div>@sensor.Displayes мм рт. ст.</div>
                            <div><input type="button" onclick="editsensorpress(@sensor.Id)" class="buttonBlue" value="Змінити" /></div>
                        </div>
                        <div id="@string.Format("editsensorpress{0}",@sensor.Id)" class="hidden">
                            <div><input style="width: 70%; " id="@string.Format("numbersensorpress{0}",@sensor.Id)" type="number" placeholder="@sensor.Displayes" /></div>
                            <div><input type="button" onclick="savesensorpress(@sensor.Id)" style="max-height: 60%" class="buttonBlue" value="Зберегти" /></div>
                        </div>
                    </div>
                </div>
                }
            </div>
        </div>
    </div>
</div>
<script>
    window.setmaintemp = '@Url.Action("SetMainTemp", "MeteoStation")';
    window.setmainpress = '@Url.Action("SetMainPress", "MeteoStation")';
    window.setsensortemp = '@Url.Action("SetSensorTemp", "MeteoStation")';
    window.setsensorpress = '@Url.Action("SetSensorPress", "MeteoStation")';

</script>